#! /usr/bin/bash

function secondMenu()
{   
    # # Create Table function
    # function createTable()
    # {
    #     echo "=========== Important Note ===========
    #     - Do not use special characters
    #     - Do not use numbers at the first
    #     "
    #     read -p "Enter table name: " tableName1
    #     if [[ "$tableName1" =~ ^[a-zA-Z]+[0-9]*" "?[a-zA-Z]*[0-9]*$ ]]
    #     then touch "$tableName1.sh"; touch "$tableName1.meta"; echo "$tableName1" table created sucessfully.
    #     elif [[ -d "$tableName1" ]]
    #     then echo "It's already exist, please user another name."
    #     else echo "Invaild name."
    #     fi   
    # }

    # List Table function
    function listTable()
    {
        ls -l;
        echo "listed successfully"
    }

    # # Drop Table function
    # function dropTable()
    # {
    #     read -p "Enter table name: " tableName3
    #     if [[ "$tableName3" = "" ]]
    #     then echo "Empty input, please enter table name."
    #     elif [[ -f "$tableName3.sh" && -f "$tableName3.meta" ]]
    #     then rm -rf "$tableName3.sh"; rm -rf "$tableName3.meta"; echo "$tableName3" table removed sucessfully 
    #     else echo "It is not exist."
    #     fi   
    # }

    # # Insert into Table function
    # function createTable()
    # {   
    
    # }

    # # Select from Table function
    # function createTable()
    # {   
    
    # }

    # # Delete from Table function
    # function createTable()
    # {   
    
    # }

    # # Update into Table function
    # function createTable()
    # {   
    
    # }
    
    # The core of second menu function
    while true; do
        echo "============= Hello in the DB ============="
        echo ">>> How could we help you? 
        1. Create table
        2. List table           
        3. Drop table	  	 
        4. Insert into table 
        5. Select from table
        6. Delete from table
        7. Update into table
        8. Exit
        ================================="    
        read -p ">>> please select a number: " secondChoice

        if [[ "$secondChoice" =~ ^[a-zA-Z]+[0-9]*" "?[a-zA-Z]*[0-9]*$ ]]
        then echo "Invalid input"
        elif [[ "$secondChoice" -eq 1 ]]
        then createTable
        elif [[ "$secondChoice" -eq 2 ]]
        then listTable
        elif [[ "$secondChoice" -eq 3 ]]
        then dropTable
        elif [[ "$secondChoice" -eq 4 ]]
        then insertIntoTable
        elif [[ "$secondChoice" -eq 5 ]]
        then selectFromTable
        elif [[ "$secondChoice" -eq 6 ]]
        then DeleteFromTable
        elif [[ "$secondChoice" -eq 7 ]]
        then updateIntoTable
        elif [[ "$secondChoice" -eq 8 ]]
        then break
        else echo "Invalid input"
        fi 
    done
}

# ================================================================================
# ================================================================================

# First menu function
function firstMenu()
{
    # # Create DB function
    # function createDB()
    # {   
    #     echo "=========== Important Note ===========
    #     - Do not use special characters
    #     - Do not use numbers at the first
    #     "
    #     read -p "Enter DB name: " dbName1
    #     if [[ "$dbName1" =~ ^[a-zA-Z]+[0-9]*" "?[a-zA-Z]*[0-9]*$ ]]
    #     then mkdir "$dbName1"; cd "$dbName1"; echo "$dbName1" created sucessfully and now you are in it.; secondMenu
    #     elif [[ -d "$dbName1" ]]
    #     then echo "It's already exist, please user another name."
    #     else echo "Invaild name."
    #     fi
    # }

    # # List DB function
    # function listDB()
    # {   
    #     read -p "Enter DB name (Click "Enter" to list the current DB): " dbName2
    #     if [[ "$dbName2" = "" ]]
    #     then ls -l ; echo "Current DB listed sucessfully"
    #     elif [[ -d "$dbName2" ]]
    #     then ls -l "$dbName2"; echo "$dbName2" listed sucessfully. 
    #     else echo "It is not exist."
    #     fi
    # }

    # Drop DB function
    function dropDB()
    {   
        read -p "Enter DB name: " dbName3
        if [[ "$dbName3" = "" ]]
        then echo "Empty input, please enter DB name."
        elif [[ -d "$dbName3/" ]]
        then rm -rf "$dbName3/"; echo "$dbName3" removed sucessfully 
        else echo "It is not exist."
        fi
    }

    # Connect DB function
    function connectDB()
    {   
        read -p "Enter DB name: " dbName4
        if [[ "$dbName4" = "" ]]
        then echo "Empty input, please enter DB name."
        elif [[ -d "$dbName4" ]]
        then cd "$dbName4"; echo "Connected successfully to $dbName4" DB; secondMenu
        else echo "It is not exist."
        fi
    }

    # The core of first menu function
    while true; do
        echo ""
        echo "============= Hello to our DBMS ============="
        echo ">>> How could we help you? 
        1. Create DB
        2. List DB
        3. Drop DB
        4. Connect DB
        5. Exit
        ================================="    
        read -p ">>> please select a number: " firstChoice
        if [[ "$firstChoice" =~ ^[a-zA-Z]+[0-9]*" "?[a-zA-Z]*[0-9]*$ ]]
        then echo "Invalid input"
        elif [[ "$firstChoice" -eq 1 ]]
        then createDB
        elif [[ "$firstChoice" -eq 2 ]]
        then listDB
        elif [[ "$firstChoice" -eq 3 ]]
        then dropDB
        elif [[ "$firstChoice" -eq 4 ]]
        then connectDB
        elif [[ "$firstChoice" -eq 5 ]]
        then break
        else echo "Invalid input"
        fi 
    done
}

firstMenu




