#! /user/bin/bash
function createDb {
    read -p "Enter your Name: " dbname
    if [[ $dbname = "" ]] ;then 
        echo "please enter name to DBMS"
    elif [[ $dbname =~ [/.:~#*\|\-] ]];then
        echo "plese donot enter spcial charter"
    elif [[ $dbname =~ ^[+(0-9)] ]];then
        echo "please enter name not star with number"
    elif [[ -e $dbname ]];then
        echo "this data base all already exists"
    elif [[ $dbname =~ ^[a-zA-Z] ]];then 
        mkdir $dbname
    fi
}

function listDb {
    read -p "Enter your Name: " ls
    if [[ $ls = "" ]]
    then
    ls -l
    elif [[ $ls = -l ]]
    then
    ls -l
    elif [[ $ls = -a ]]
    then
    ls -a
    elif [[ $ls = -t ]]
    then
    ls -t
    elif [[ $ls = -r ]]
    then
    ls -r
    elif [[ $ls = -S ]]
    then
    ls -S
    elif [[ $ls = -R ]]
    then
    ls -R
    elif [[ $ls = -i ]]
    then
    ls -i
    elif [[ $ls = -g ]]
    then
    ls -g
    elif [[ $ls = -h ]]
    then
    ls -h
    elif [[ $ls = -d ]]
    then
    ls -d
    else 
    echo "enter thing relateve ls"
    fi
}
function createtable {
    read -p "Enter your Name: " table
    if [[ $table = "" ]] ;then 
        echo "please enter name to table"
    elif [[ $table =~ [/.:~#*\|\-] ]];then
        echo "plese donot enter spcial charter"
    elif [[ $table =~ ^[+(0-9)] ]];then
        echo "please enter name not star with number"
    elif [[ -e $table ]];then
        echo "this table all already exists"
    elif [[ $table =~ ^[a-zA-Z] ]];then 
        touch $table
    fi

    if [[ -f $table ]]; then
        valid=true
        while $valid ;do
            read -p  "enter number of colums: " numcol
            if [[ $numcol = +([1-9])*([0-9]) ]];then
                valid=false
            fi
        done
        valid=true
        while $valid;do
            read -p "enter name of pk"
            if [[ $pk = "" ]] ;then 
                echo "please enter name to pk"
            elif [[ $pk =~ [/.:~#*\|\-] ]];then
                echo "plese donot enter spcial charter"
            elif [[ $pk =~ ^[+(0-9)] ]];then
                echo "please enter name not star with number"
            elif [[ -e $pk ]];then
                echo "this data base all already exists"
            elif [[ $pk =~ ^[a-zA-Z] ]];then 
                echo -n "$pk" >> "$table"
                echo -n "-" >> "$table"
                valid=false

            fi
        done

        valid=true
        while $valid; do
            read -p "enter int or str: " option
                if [[ "$option" = "int" || "$option" = "str" ]]; then
                    echo -n "$option" >> "$table"
                    echo -n "-" >> "$table"
                    valid=false
                else
                    echo  "please enter in int or str"
                fi

        done

        valid=true
        while $valid; do
            read -p "enter size pk: "size
            if [[ $size = +([1-9])*([0-9]) ]]; then
                echo -n "$size" >> "$dbtable"
                echo -n ":" >> "$dbtable"
                valid=false
            else
                echo  "please enter number"
            fi
        done






    fi
        



}
